CREATE OR REPLACE PROCEDURE SP_GET_HISTORICO_EQUIPOS(
  PV_CEDULA IN VARCHAR2
)
AS
BEGIN
  SELECT F.NOMBRES, E.NOMBRE_EQUIPO, H.FECHA_INICIO, H.FECHA_FIN
  FROM FUTBOLISTA F
  INNER JOIN HISTORICO_EQUIPOS H ON H.CEDULA = F.CEDULA
  INNER JOIN EQUIPOS E ON E.ID_EQUIPO = H.ID_EQUIPO
  WHERE F.CEDULA = PV_CEDULA;
END;
