CREATE OR REPLACE PROCEDURE SP_INS_FUTBOLISTA(
  PV_CEDULA IN VARCHAR2,
  PV_NOMBRES IN VARCHAR2,
  PV_APELLIDOS IN VARCHAR2,
  PV_FECHA_NACIMIENTO IN DATE,
  PV_PAIS IN VARCHAR2,
  PV_DIRECCION IN VARCHAR2,
  PV_DESCRIPCION IN VARCHAR2
)
AS
  CONTADOR_ID INTEGER;
BEGIN
  SELECT CEDULA INTO CONTADOR_ID
  FROM FUTBOLISTA
  WHERE ROWNUM = 1;

  INSERT INTO FUTBOLISTA(CEDULA, NOMBRES, APELLIDOS, FECHA_NACIMIENTO, PAIS, DIRECCION, DESCRIPCION)
  VALUES(PV_CEDULA, PV_NOMBRES, PV_APELLIDOS, PV_FECHA_NACIMIENTO, PV_PAIS, PV_DIRECCION, PV_DESCRIPCION);
END;