CREATE OR REPLACE PROCEDURE SP_INS_EQUIPOS(
  PV_NOMBRE_EQUIPO IN VARCHAR2,
  PV_DESCRIPCION IN VARCHAR2,
  PV_NUMERO_JUGADORES IN VARCHAR2,
  PV_PAIS IN VARCHAR2,
  PV_FALTAS IN VARCHAR2,
  PV_CIUDAD IN VARCHAR2,
  PV_ESTADIO IN VARCHAR2
)
AS
  CONTADOR_ID INTEGER;
BEGIN
  SELECT NOMBRE_EQUIPO INTO CONTADOR_ID
  FROM EQUIPOS
  WHERE ROWNUM = 1;

  INSERT INTO EQUIPOS(NOMBRE_EQUIPO, DESCRIPCION, NUMERO_JUGADORES, PAIS, FALTAS, CIUDAD, ESTADIO)
  VALUES(PV_NOMBRE_EQUIPO, PV_DESCRIPCION, PV_NUMERO_JUGADORES, PV_PAIS, PV_FALTAS, PV_CIUDAD, PV_ESTADIO);
END;