CREATE OR REPLACE PROCEDURE SP_UPD_FUTBOLISTA(
  PV_CEDULA IN VARCHAR2,
  PV_NOMBRES IN VARCHAR2,
  PV_APELLIDOS IN VARCHAR2,
  PV_FECHA_NACIMIENTO IN DATE,
  PV_PAIS IN VARCHAR2,
  PV_DIRECCION IN VARCHAR2,
  PV_DESCRIPCION IN VARCHAR2
)
AS
BEGIN
  UPDATE FUTBOLISTA
  SET NOMBRES = PV_NOMBRES,
      APELLIDOS = PV_APELLIDOS,
      FECHA_NACIMIENTO = PV_FECHA_NACIMIENTO,
      PAIS = PV_PAIS,
      DIRECCION = PV_DIRECCION,
      DESCRIPCION = PV_DESCRIPCION
  WHERE CEDULA = PV_CEDULA;
END;