CREATE TABLE FUTBOLISTA(
  CEDULA VARCHAR2(50) PRIMARY KEY,
  NOMBRES VARCHAR2(50),
  APELLIDOS VARCHAR2(50),
  FECHA_NACIMIENTO DATE,
  PAIS VARCHAR2(50),
  DIRECCION VARCHAR2(50),
  DESCRIPCION VARCHAR2(50)
);

CREATE TABLE EQUIPOS(
  ID_EQUIPOS NUMBER PRIMARY KEY,
  NOMBRE_EQUIPO VARCHAR2(50),
  DESCRIPCION VARCHAR2(50),
  NUMERO_JUGADORES NUMBER,
  PAIS VARCHAR2(50),
  FALTAS NUMBER,
  CIUDAD VARCHAR2(50),
  ESTADIO VARCHAR2(50)
);

CREATE TABLE HISTORICO_EQUIPOS(
  ID_HISTORICO_EQUIPOS NUMBER PRIMARY KEY,
  CEDULA VARCHAR2(50),
  ID_EQUIPO NUMBER,
  FECHA_INICIO DATE,
  FECHA_FIN DATE
);

ALTER TABLE HISTORICO_EQUIPOS
ADD CONSTRAINT fk_equipo FOREIGN KEY (ID_EQUIPO)
REFERENCES EQUIPOS (ID_EQUIPOS);